import { useState } from 'react';
import { DataBar } from './components/DataBar';
import { MetricCard } from './components/MetricCard';

type Report = { dataset_name: string; total_cases: number; passed_cases: number; pass_rate: number; by_difficulty: Record<string, { total_cases: number; passed_cases: number; pass_rate: number }>; failure_clusters: Array<{ signature: string; count: number; case_ids: string[] }> };

export function EvaluationView() {
  const [report, setReport] = useState<Report | null>(null);
  const [error, setError] = useState('');
  async function load(file: File) { try { const value = JSON.parse(await file.text()) as Report; if (!value.dataset_name || !Array.isArray(value.failure_clusters)) throw new Error(); setReport(value); setError(''); } catch { setError('请选择 agent-devtools evaluate 生成的 JSON 报告。'); } }
  return <section className="panel panel-full evaluation-view"><div className="evaluation-header"><div><h2 className="panel-heading">评测报告</h2><p className="muted">导入本地评测 JSON 查看质量门禁和失败聚类。</p></div><label className="btn btn-secondary">导入报告<input aria-label="导入评测报告" type="file" accept="application/json,.json" onChange={e => e.target.files?.[0] && load(e.target.files[0])} /></label></div>{error && <p className="evaluation-error">{error}</p>}{!report && !error && <div className="empty-state"><h3>暂无评测报告</h3><p>运行 evaluate 命令并导入其 --output 文件。</p></div>}{report && <><div className="metrics-row"><MetricCard label="数据集" value={report.dataset_name}/><MetricCard label="通过率" value={`${(report.pass_rate * 100).toFixed(0)}%`} kind={report.pass_rate >= .7 ? 'accent' : 'error'}/><MetricCard label="通过" value={`${report.passed_cases}/${report.total_cases}`}/><MetricCard label="失败簇" value={report.failure_clusters.length} kind={report.failure_clusters.length ? 'warn' : 'accent'}/></div><div className="evaluation-grid"><div className="evaluation-section"><h3>难度分层</h3>{Object.entries(report.by_difficulty).map(([difficulty, row]) => <DataBar key={difficulty} label={`${difficulty} ${row.passed_cases}/${row.total_cases}`} value={row.pass_rate} max={1} kind={row.pass_rate >= .7 ? 'accent' : 'warn'}/>)}</div><div className="evaluation-section"><h3>失败聚类</h3>{report.failure_clusters.length ? <table className="data-table"><thead><tr><th>签名</th><th className="num">次数</th><th>Case</th></tr></thead><tbody>{report.failure_clusters.map(cluster => <tr key={cluster.signature}><td className="mono">{cluster.signature}</td><td className="num">{cluster.count}</td><td>{cluster.case_ids.join(', ')}</td></tr>)}</tbody></table> : <p className="muted">没有失败簇。</p>}</div></div></>}</section>;
}
